In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import os

In [2]:
# load ratings
path = os.path.abspath(os.path.join((os.getcwd()),  os.pardir, "data\\recommendation\\rating.csv") )
ratings = pd.read_csv(path)
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [1]:
ratings.shape

NameError: name 'ratings' is not defined

In [4]:
ratings.groupby("userId")["movieId"].count().min()
#each user has rated atleast 20 movies

20

In [5]:
# limits
n_users = 5000
n_movies = 1000

top_users = ratings['userId'].value_counts().head(n_users).index.tolist() ## users who rated more number of movies
top_movies = ratings['movieId'].value_counts().head(n_movies).index.tolist() ## movies that received more number of ratings

In [6]:
filtered = ratings[ratings['userId'].isin(top_users) & ratings['movieId'].isin(top_movies)]
filtered.shape

(2353665, 4)

In [7]:
filtered.groupby("userId")["movieId"].count().sort_values(ascending=False)

userId
8405      999
88604     994
118205    988
118754    964
74142     952
         ...
15452     118
24443     114
59931     104
65687      87
42229      35
Name: movieId, Length: 5000, dtype: int64

In [8]:
filtered[filtered["userId"] == 42229]["rating"].value_counts()

rating
5.0    11
3.5     7
4.0     6
2.0     4
4.5     3
3.0     2
1.5     1
2.5     1
Name: count, dtype: int64

In [9]:
ratings[ratings["userId"] == 8405]["rating"].value_counts()

rating
4.0    1531
3.0    1442
2.5    1131
3.5    1084
2.0     900
4.5     534
5.0     438
1.5     382
1.0      73
Name: count, dtype: int64

In [10]:
filtered.groupby("movieId")["userId"].count().sort_values(ascending=False)

movieId
2571    4732
356     4691
1270    4669
480     4668
296     4643
        ...
207      811
637      772
276      770
79       629
140      581
Name: userId, Length: 1000, dtype: int64

In [11]:
user_movie_df = filtered.pivot_table(index="userId", columns="movieId", values="rating")
user_movie_matrix = user_movie_df.fillna(0)
user_movie_matrix

movieId,1,2,3,5,6,7,10,11,14,16,...,70286,71535,72998,73017,74458,78499,79132,80463,81591,81845
userId,,,,,,,,,,,,,,,,,,,,,
54,4.0,3.0,0.0,3.0,3.0,0.0,4.0,5.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,5.0,0.0,0.0,0.0,4.5,0.0,0.0,4.5,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91,4.0,3.5,3.0,0.0,0.0,2.5,4.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
116,3.0,2.0,2.0,0.0,1.5,0.0,2.0,2.0,0.0,3.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138325,5.0,3.0,0.0,0.0,4.5,0.0,3.5,0.0,0.0,4.5,...,4.5,4.5,3.5,0.0,4.0,5.0,4.5,4.5,4.5,5.0
138382,3.0,4.0,3.0,0.0,0.0,3.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138397,0.0,0.0,5.0,0.0,5.0,0.0,4.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138406,4.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.5,0.0,4.0
138437,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,5.0,4.0,3.5,0.0,3.5,4.0,4.5,4.0,4.0,0.0

## User based CF

In [12]:
user_sim = cosine_similarity(user_movie_matrix) # similarity_matrix[i][j] = similarity between user i and user j
user_sim_df = pd.DataFrame(user_sim, index=user_movie_df.index, columns=user_movie_df.index)
user_sim_df

userId,54,58,91,104,116,156,208,271,294,298,...,138211,138254,138270,138301,138307,138325,138382,138397,138406,138437
userId,,,,,,,,,,,,,,,,,,,,,
54,1.000000,0.547123,0.531749,0.449013,0.522661,0.662074,0.525756,0.360460,0.543421,0.654510,...,0.400627,0.493111,0.530702,0.414576,0.486886,0.479598,0.620054,0.572552,0.423226,0.363397
58,0.547123,1.000000,0.578699,0.538901,0.485607,0.616222,0.631064,0.359214,0.556434,0.514658,...,0.464117,0.521729,0.561207,0.492370,0.549470,0.621205,0.494220,0.529059,0.509357,0.464631
91,0.531749,0.578699,1.000000,0.469473,0.589310,0.604817,0.554775,0.512525,0.667053,0.560605,...,0.548978,0.587856,0.513551,0.530053,0.522647,0.613625,0.492813,0.574972,0.538413,0.497103
104,0.449013,0.538901,0.469473,1.000000,0.279076,0.476359,0.610900,0.207724,0.397437,0.286026,...,0.353751,0.267870,0.538606,0.393347,0.490816,0.611429,0.347663,0.331793,0.384992,0.327474
116,0.522661,0.485607,0.589310,0.279076,1.000000,0.587215,0.441212,0.521328,0.619177,0.642129,...,0.520769,0.653749,0.434284,0.503389,0.438368,0.497056,0.511029,0.565360,0.502869,0.503115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138325,0.479598,0.621205,0.613625,0.611429,0.497056,0.534240,0.719528,0.512025,0.624426,0.387323,...,0.519936,0.549642,0.550825,0.623471,0.630409,1.000000,0.408288,0.499713,0.613723,0.637496
138382,0.620054,0.494220,0.492813,0.347663,0.511029,0.642799,0.415615,0.376889,0.505980,0.662916,...,0.390604,0.525286,0.457369,0.346077,0.396641,0.408288,1.000000,0.507327,0.403541,0.294775
138397,0.572552,0.529059,0.574972,0.331793,0.565360,0.607327,0.431368,0.435229,0.581106,0.568498,...,0.357144,0.550453,0.435667,0.468376,0.402111,0.499713,0.507327,1.000000,0.449442,0.407179
138406,0.423226,0.509357,0.538413,0.384992,0.502869,0.467160,0.497864,0.420375,0.513218,0.413703,...,0.432853,0.556135,0.419263,0.531455,0.488592,0.613723,0.403541,0.449442,1.000000,0.516444
138437,0.363397,0.464631,0.497103,0.327474,0.503115,0.380441,0.529503,0.513015,0.553199,0.345075,...,0.520190,0.558759,0.398840,0.622348,0.558748,0.637496,0.294775,0.407179,0.516444,1.000000

In [13]:
def predict_rating_user_based(user_id, movie_id, k=10): ##movie_id = unrated movie of current user
    if movie_id not in user_movie_df.columns or user_id not in user_movie_df.index:
        return np.nan
    
    movie_ratings = user_movie_df[movie_id] # get the particular movie ratings from all users
    valid_users = movie_ratings.dropna().index # remove users who have not rated that particular movie
    ratings = movie_ratings[valid_users] # get the particular movie ratings only from valid users

    sims = user_sim_df.loc[user_id]  # selecting the particular user row from the cosine similarity matrix. this will have he similarity scores of current user vs other users
    sims = sims[valid_users] # filter the similarity scores only for those valid users who rated that movie

    if sims.empty:
        return np.nan

    top_k_users = sims.sort_values(ascending=False).head(k) # filter top K users with higher similarity scores
    top_k_ratings = ratings.loc[top_k_users.index] #filter top K ratings of that particular movie by top K similar users


    pred = np.dot(top_k_users.values, top_k_ratings.values) / np.sum(np.abs(top_k_users.values)) # ratings vs similarity weighed average
    return pred

In [14]:
def recommend_top_n_user_based(user_id, n=5, k=10):
    if user_id not in user_movie_df.index:
        return []


    rated = user_movie_df.loc[user_id].dropna().index # rated movie list of an user
    unrated = [movie for movie in user_movie_df.columns if movie not in rated] # unrated movie list of an user


    predictions = []
    for movie_id in unrated: # loop all unrated movies to get recommendation
        #print(f"movie id: {movie_id}")
        pred = predict_rating_user_based(user_id, movie_id, k)  # passing each unrated movie id for that particular user to get top K predictions
        if not np.isnan(pred):
            predictions.append((movie_id, pred))
        #break

    top_n = sorted(predictions, key=lambda x: x[1], reverse=True)[:n]
    return top_n

In [15]:
top_recs_user_based = recommend_top_n_user_based(user_id=42229, n=5, k=10) #k = filter K users with highest similarity score; #n = filter top n results

print("User-based recommendations:")
for movie_id, score in top_recs_user_based:
    print(f"Movie {movie_id} → predicted rating: {score:.2f}")

User-based recommendations:
Movie 318 → predicted rating: 4.65
Movie 6016 → predicted rating: 4.49
Movie 58559 → predicted rating: 4.40
Movie 2324 → predicted rating: 4.40
Movie 2858 → predicted rating: 4.39

## Item based CF

In [16]:
# Item-based similarity calculation
item_sim = cosine_similarity(user_movie_matrix.T)
item_sim_df = pd.DataFrame(item_sim, index=user_movie_df.columns, columns=user_movie_df.columns)
item_sim_df.head()

movieId,1,2,3,5,6,7,10,11,14,16,...,70286,71535,72998,73017,74458,78499,79132,80463,81591,81845
movieId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.766482,0.543301,0.531587,0.703963,0.540227,0.742627,0.646873,0.358172,0.672434,...,0.528650,0.465902,0.544533,0.487044,0.464872,0.505247,0.540868,0.469308,0.442242,0.445726
2,0.766482,1.000000,0.519800,0.521413,0.591841,0.490483,0.681443,0.545834,0.273971,0.574333,...,0.484466,0.449009,0.506605,0.469642,0.439463,0.421740,0.499386,0.402579,0.391750,0.379017
3,0.543301,0.519800,1.000000,0.536689,0.445541,0.441930,0.507917,0.500387,0.251055,0.444221,...,0.229940,0.220094,0.247252,0.238470,0.202749,0.213028,0.237879,0.207058,0.184000,0.186749
5,0.531587,0.521413,0.536689,1.000000,0.395942,0.492047,0.473851,0.513764,0.235717,0.388996,...,0.227456,0.220086,0.264409,0.239578,0.209724,0.242553,0.251905,0.231345,0.206923,0.202518
6,0.703963,0.591841,0.445541,0.395942,1.000000,0.427751,0.685438,0.542029,0.385855,0.751148,...,0.481858,0.416750,0.454762,0.427353,0.435528,0.372837,0.483997,0.425386,0.399266,0.382268

In [17]:
def predict_rating_item_based(user_id, movie_id, k=10):
    if movie_id not in user_movie_df.columns or user_id not in user_movie_df.index:
        return np.nan


    sims = item_sim_df[movie_id]
    user_ratings = user_movie_df.loc[user_id]
    valid_items = user_ratings.dropna().index


    sims = sims[valid_items]
    ratings = user_ratings[valid_items]


    if sims.empty:
        return np.nan


    top_k_items = sims.sort_values(ascending=False).head(k)
    top_k_ratings = ratings.loc[top_k_items.index]


    pred = np.dot(top_k_items.values, top_k_ratings.values) / np.sum(np.abs(top_k_items.values))
    return pred

In [18]:
def recommend_top_n_item_based(user_id, n=5, k=10):
    if user_id not in user_movie_df.index:
        return []


    rated = user_movie_df.loc[user_id].dropna().index
    unrated = [movie for movie in user_movie_df.columns if movie not in rated]


    predictions = []
    for movie_id in unrated:
        pred = predict_rating_item_based(user_id, movie_id, k)
        if not np.isnan(pred):
            predictions.append((movie_id, pred))


    top_n = sorted(predictions, key=lambda x: x[1], reverse=True)[:n]
    return top_n

top_recs_item_based = recommend_top_n_item_based(user_id=42229, n=5, k=10)

print("\nItem-based recommendations:")
for movie_id, score in top_recs_item_based:
    print(f"Movie {movie_id} → predicted rating: {score:.2f}")

# Model Based CF

## Explicit feedback - SVD - SGD

In [19]:
from surprise import Reader, SVD, Dataset, accuracy
from surprise.model_selection import GridSearchCV, train_test_split, cross_validate, LeaveOneOut

In [20]:
reader = Reader(rating_scale=(0.5, 5))
reader

In [21]:
data = Dataset.load_from_df(filtered[['userId',
                                       'movieId',
                                       'rating']], reader)

In [22]:
data.df.head()

      userId  movieId  rating
5400      54        1     4.0
5401      54        2     3.0
5402      54        5     3.0
5403      54        6     3.0
5404      54       10     4.0

### train_test_split

In [23]:
trainset, testset = train_test_split(data, test_size=.25)
trainset.n_users

5000

In [24]:
svd_model = SVD()
svd_model.fit(trainset)

In [25]:
predictions = svd_model.test(testset)
accuracy.rmse(predictions)

RMSE: 0.7235

0.7234757972509446

In [26]:
svd_model.predict(uid=1.0, iid=541, r_ui=4.0, verbose=True)

user: 1.0        item: 541        r_ui = 4.00   est = 3.97   {'was_impossible': False}

Prediction(uid=1.0, iid=541, r_ui=4.0, est=3.9745673806047335, details={'was_impossible': False})

In [27]:
ratings[(ratings["userId"] == 1) & (ratings["movieId"] == 541)]

    userId  movieId  rating            timestamp
15       1      541     4.0  2005-04-02 23:30:03

### Get Top N recommendations for all users

In [28]:
from collections import defaultdict

from surprise import Dataset, SVD


def get_top_n(predictions, n=10):
    """Return the top-N recommendation for each user from a set of predictions.

    Args:
        predictions(list of Prediction objects): The list of predictions, as
            returned by the test method of an algorithm.
        n(int): The number of recommendation to output for each user. Default
            is 10.

    Returns:
    A dict where keys are user (raw) ids and values are lists of tuples:
        [(raw item id, rating estimation), ...] of size n.
    """

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

In [29]:
top_n = get_top_n(predictions, n=5)

# Print the recommended items for each user
movie_ids = []
for uid, user_ratings in top_n.items():
        movie_ids = [iid for (iid,_) in user_ratings]
        print(uid, movie_ids)

14808 [3578, 7153, 50, 4855, 2762]
137885 [1272, 904, 912, 2366, 1228]
91349 [2019, 922, 541, 912, 1212]
121535 [1207, 1221, 1219, 908, 1204]
65387 [1219, 5060, 1080, 2010, 1965]
103701 [2959, 50, 6016, 44555, 58559]
85986 [1201, 2858, 50, 60069, 6711]
131721 [318, 3949, 1193, 3160, 1210]
60887 [5669, 296, 1407, 1307, 50]
124967 [969, 50, 1214, 4720, 2692]
107317 [1221, 4848, 1219, 908, 535]
30835 [4993, 30793, 4720, 8970, 2542]
135418 [33794, 7147, 4878, 50, 4226]
22205 [79132, 318, 3949, 81591, 6874]
104977 [5971, 2329, 1298, 480, 260]
15203 [2791, 1198, 1213, 4002, 1288]
26884 [858, 903, 5060, 1203, 3072]
87954 [920, 40815, 8368, 6874, 4367]
66952 [296, 1203, 293, 6016, 4973]
100367 [5952, 4993, 2959, 4973, 593]
103199 [1266, 3504, 527, 246, 1214]
98687 [589, 1198, 2916, 5952, 1036]
35510 [7153, 4993, 2028, 1221, 1219]
57626 [33166, 2959, 4226, 58559, 7361]
128653 [1073, 1298, 29, 1285, 1032]
23437 [1250, 7153, 260, 1201, 720]
41281 [47, 2542, 2858, 858, 1233]
18007 [541, 4979, 750, 1212, 858]
118596 [50, 3578, 1242, 7254, 5952]
51994 [2918, 5971, 2144, 5618, 4308]
103973 [79132, 53996, 296, 318, 5378]
38251 [1278, 260, 1193, 1225, 1196]
127390 [2081, 1022, 1029, 2087, 587]
132947 [1197, 2571, 1219, 858, 1193]
49999 [4993, 110, 1210, 104, 3552]
109186 [595, 597, 1380, 2115, 2795]
31616 [318, 5952, 6539, 527, 72998]
9834 [4995, 2329, 1270, 3916, 2028]
105081 [50, 903, 2313, 293, 1267]
122704 [2858, 858, 1193, 1213, 7153]
82082 [551, 2010, 1199, 1394, 1197]
88527 [589, 260, 1198, 1036, 1221]
394 [2019, 162, 1256, 750, 1212]
134535 [858, 527, 356, 920, 608]
119677 [1732, 1221, 1968, 2423, 1210]
741 [1204, 1207, 1960, 1193, 2359]
78681 [1199, 162, 5618, 1394, 924]
134215 [1219, 1207, 858, 318, 1358]
73787 [50, 296, 1221, 260, 1196]
128047 [4306, 1197, 4886, 54001, 595]
30092 [6016, 4226, 318, 778, 2997]
65409 [7361, 50, 2959, 2858, 296]
57716 [296, 924, 1214, 1221, 1263]
71328 [16, 1089, 1258, 2329, 2959]
125621 [40815, 899, 1207, 745, 1148]
113129 [2571, 2028, 3578, 5952, 47]
88833 [2959, 3147, 2908, 1339, 1653]
61616 [3552, 3421, 2918, 1215, 58559]
117054 [912, 1234, 1221, 2396, 922]
70068 [318, 527, 72998, 3578, 1704]
64638 [923, 296, 2858, 1148, 903]
77007 [912, 1212, 296, 908, 1250]
56434 [2858, 47, 608, 562, 25]
112742 [79132, 47, 1252, 55820, 1089]
39766 [1208, 924, 2324, 1219, 1203]
107087 [3578, 318, 6, 2028, 805]
69378 [162, 541, 260, 908, 1213]
60834 [7361, 1206, 318, 32, 1199]
125696 [923, 924, 296, 1952, 3424]
15486 [260, 293, 4995, 4085, 2268]
96218 [68954, 6377, 1, 2858, 4306]
4428 [7153, 1197, 912, 4963, 4306]
63596 [1230, 908, 3000, 4993, 6377]
66837 [1219, 904, 111, 1193, 1206]
99156 [1252, 111, 904, 527, 1230]
48068 [1198, 2762, 4226, 858, 1954]
10514 [296, 260, 4226, 7361, 48516]
42369 [745, 1207, 5618, 58559, 1198]
106308 [912, 1252, 903, 908, 2019]
53908 [1198, 1196, 589, 2571, 1036]
67053 [1214, 1253, 1732, 1258, 2916]
21664 [50, 903, 913, 1234, 1213]
88803 [1356, 2193, 1748, 2005, 2161]
31121 [1197, 1035, 908, 2078, 1234]
49904 [296, 50, 293, 1201, 2858]
104249 [904, 923, 1947, 1193, 2804]
5832 [953, 954, 527, 1252, 910]
13049 [8874, 2959, 4226, 5673, 1196]
77630 [47, 2329, 858, 5952, 296]
132846 [7153, 3578, 2762, 1196, 1197]
95895 [1256, 2700, 2300, 1249, 38061]
5482 [48394, 919, 1235, 1247, 3967]
25093 [1196, 1387, 480, 908, 1221]
4598 [4993, 1203, 5618, 2959, 2762]
16948 [2858, 551, 3996, 1258, 1214]
94773 [296, 1148, 745, 1288, 2300]
115617 [4979, 1230, 1172, 1235, 1288]
64326 [5971, 293, 2324, 1208, 1210]
126395 [2858, 296, 527, 50, 2028]
51608 [800, 593, 541, 904, 318]
47120 [296, 1258, 1214, 1221, 541]
136268 [1393, 1198, 1090, 1270, 377]
99360 [1196, 260, 4993, 1262, 1210]
27469 [1213, 593, 55820, 608, 1198]
100506 [2918, 1704, 216, 50, 1101]
81706 [1197, 78499, 1148, 293, 72998]
80561 [1258, 541, 1527, 318, 750]
118631 [2918, 1968, 2797, 318, 5060]
49824 [50, 4720, 2762, 3081, 1527]
21861 [260, 2019, 1394, 2300, 2761]
38988 [6874, 5952, 923, 7438, 1089]
73348 [1198, 1291, 260, 318, 1210]
105588 [1200, 1258, 1333, 858, 1266]
14994 [4993, 1204, 5618, 1214, 2010]
30857 [480, 356, 1198, 590, 1721]
100781 [1254, 2019, 750, 111, 1212]
52457 [81845, 1197, 44555, 44665, 6539]
27810 [1, 34, 2797, 1270, 1197]
44388 [1196, 318, 1, 593, 2858]
108067 [2908, 2959, 1206, 1230, 858]
34576 [593, 58559, 4226, 2329, 1214]
68161 [318, 356, 1198, 260, 68358]
120524 [589, 2021, 32, 5618, 1676]
33402 [922, 593, 2700, 247, 2160]
96608 [1230, 4973, 527, 1252, 1185]
39809 [4993, 1221, 912, 318, 7090]
104803 [1580, 1721, 1028, 2424, 11]
7472 [527, 318, 922, 50, 1035]
108393 [904, 858, 1212, 5618, 1252]
117705 [7153, 4896, 318, 2628, 7143]
66836 [4848, 1221, 541, 296, 912]
54305 [1221, 608, 1252, 1213, 1219]
46929 [5618, 58559, 293, 1197, 593]
119734 [318, 5995, 1203, 4226, 63082]
66635 [2019, 858, 1203, 903, 1945]
21378 [6016, 2959, 318, 111, 356]
37051 [2571, 72998, 2762, 7153, 527]
67303 [1610, 150, 110, 5418, 3256]
79877 [1206, 1252, 527, 1219, 904]
80337 [1207, 541, 858, 1203, 318]
114009 [2329, 50, 541, 6016, 306]
7487 [1, 1196, 1288, 111, 60069]
45060 [318, 593, 1203, 2762, 2194]
116263 [333, 2144, 2762, 1259, 356]
82901 [2918, 2795, 1193, 231, 1198]
116498 [81845, 50, 954, 1246, 912]
135522 [4973, 1732, 2959, 3996, 48394]
10229 [6539, 2485, 588, 7293, 4018]
84849 [858, 4993, 5618, 920, 318]
59447 [1208, 912, 1206, 44555, 6016]
42935 [2571, 1206, 858, 4262, 32]
128003 [953, 1276, 1304, 915, 913]
24219 [4226, 2329, 110, 55820, 48516]
110607 [1188, 50, 1199, 29, 1175]
103668 [2571, 2542, 60069, 60684, 1215]
52698 [1196, 2019, 6016, 8961, 1207]
130716 [6016, 260, 1213, 1291, 2019]
127901 [7153, 2858, 2329, 296, 2692]
132603 [2959, 1213, 1203, 44555, 7153]
2930 [318, 7153, 4896, 1197, 356]
74814 [2019, 1206, 1252, 923, 1952]
5138 [908, 2019, 1203, 923, 1252]
51227 [1208, 1258, 5618, 2959, 4848]
101372 [1252, 1250, 1267, 1208, 162]
16612 [1206, 1222, 318, 223, 1089]
54113 [1148, 750, 908, 858, 910]
67518 [2423, 2571, 1196, 260, 5418]
7051 [7153, 541, 1193, 593, 8961]
102131 [1196, 7153, 1208, 5952, 2019]
120067 [5618, 2571, 4226, 2019, 1203]
6636 [1206, 2959, 296, 2858, 1252]
95254 [1258, 2160, 111, 908, 2019]
49285 [1212, 1252, 2019, 3608, 903]
6166 [1945, 923, 1213, 1136, 46578]
42692 [318, 7438, 6874, 6377, 593]
4914 [858, 318, 296, 50, 356]
63236 [1254, 919, 1965, 969, 1201]
98470 [2959, 1213, 2997, 750, 778]
122364 [1210, 1036, 2804, 110, 296]
72665 [356, 1196, 589, 3256, 2396]
76213 [246, 56782, 858, 4226, 1089]
23832 [1291, 1221, 480, 590, 293]
66617 [858, 1252, 904, 1199, 1256]
64778 [1252, 50, 1204, 296, 750]
95501 [318, 858, 47, 50, 1201]
16581 [1228, 1208, 923, 55820, 1089]
87846 [1291, 1270, 2716, 3000, 1036]
36048 [4973, 5618, 5669, 318, 296]
70025 [1208, 858, 1175, 923, 162]
78954 [318, 7361, 4878, 1213, 33794]
90462 [60069, 745, 7361, 318, 2858]
74966 [2858, 1269, 296, 2762, 6539]
69473 [858, 296, 79132, 68358, 5903]
101458 [2762, 8961, 377, 1907, 4993]
57543 [2324, 50, 2396, 1307, 745]
94259 [4993, 5952, 2959, 1291, 318]
21850 [1188, 2908, 509, 1225, 551]
99871 [1732, 296, 318, 180, 54503]
132509 [2959, 7361, 296, 47, 3949]
78340 [5669, 2858, 4973, 1041, 1247]
99930 [2858, 4993, 1201, 2329, 527]
121930 [47, 7361, 7438, 6016, 1208]
119214 [1210, 2700, 1136, 4011, 223]
14977 [318, 593, 4226, 1258, 750]
88820 [1198, 1193, 919, 1250, 608]
130809 [50, 1089, 110, 4993, 1259]
89458 [1252, 1221, 924, 1201, 541]
63192 [2858, 4973, 3052, 3897, 1193]
50958 [1221, 2804, 1247, 858, 1252]
59230 [318, 1270, 1198, 1291, 1196]
65219 [296, 4993, 260, 1200, 1210]
8924 [50, 47, 3275, 2542, 1036]
6366 [858, 1213, 1276, 1225, 1233]
119067 [1721, 4306, 318, 4995, 2125]
66810 [111, 2959, 1208, 1258, 2076]
17818 [593, 1258, 1221, 1968, 1997]
61525 [914, 903, 5991, 44191, 899]
121543 [1213, 1201, 1206, 908, 541]
57240 [1270, 1, 2571, 480, 588]
96954 [1967, 527, 293, 1193, 81845]
136875 [2571, 593, 6874, 68157, 1291]
46579 [1198, 318, 1201, 1200, 293]
128527 [1198, 1196, 1240, 1028, 1200]
13589 [1086, 8368, 2359, 2125, 5060]
113256 [922, 912, 913, 899, 904]
95037 [2959, 4848, 5618, 1233, 1214]
125546 [593, 1240, 1242, 1291, 2194]
121381 [1196, 2019, 541, 720, 1387]
78356 [2858, 296, 50, 858, 1358]
8459 [1215, 1201, 1732, 1213, 2076]
7434 [2959, 50, 858, 6016, 4993]
115800 [608, 1244, 908, 903, 899]
13991 [1136, 2028, 593, 111, 1374]
28651 [50, 1210, 260, 33794, 1291]
131053 [356, 969, 1, 4306, 260]
43122 [1212, 608, 2186, 541, 2291]
98231 [1610, 1196, 2000, 1356, 377]
11434 [5618, 2700, 6874, 1200, 1982]
80391 [1214, 1198, 1208, 527, 1262]
127713 [50, 5995, 1299, 1252, 1203]
97770 [3552, 2795, 1221, 296, 1089]
105607 [1252, 593, 1213, 7361, 1230]
37764 [1219, 527, 1387, 246, 50]
33082 [4226, 541, 2692, 68954, 4973]
44070 [1036, 59315, 2716, 1, 33794]
126157 [858, 1263, 356, 318, 1258]
43451 [7153, 4993, 2542, 2858, 593]
24691 [1221, 1208, 260, 55820, 48516]
132415 [593, 1207, 2908, 1104, 1249]
56351 [7361, 4993, 3996, 3949, 745]
135183 [527, 2762, 356, 150, 589]
130516 [1196, 318, 593, 3578, 858]
107266 [2804, 4226, 593, 318, 50]
95149 [2959, 1214, 260, 318, 1222]
34758 [4226, 7361, 56782, 4979, 68157]
102197 [1193, 593, 1208, 904, 1250]
137558 [750, 923, 111, 912, 1206]
134859 [296, 858, 47, 1201, 2076]
35424 [50, 1208, 778, 1089, 6874]
20969 [50, 2858, 5618, 6711, 858]
111881 [541, 293, 4226, 1193, 1206]
100804 [2959, 1258, 924, 1965, 1089]
48038 [7361, 1394, 5673, 1968, 778]
13338 [750, 260, 1387, 1206, 858]
133475 [46578, 7361, 3556, 4979, 2918]
108316 [44555, 1193, 111, 2329, 2959]
22189 [5618, 4993, 1148, 5971, 1225]
40483 [858, 1252, 1204, 903, 1212]
23459 [904, 750, 923, 720, 7361]
47860 [1270, 589, 2959, 1682, 79132]
74879 [260, 527, 1210, 50, 2028]
3576 [899, 922, 904, 1252, 750]
63574 [1288, 34, 750, 1148, 1]
90093 [318, 858, 260, 1198, 1197]
971 [1258, 858, 1221, 1206, 750]
115416 [4226, 1288, 1136, 2997, 4993]
39099 [750, 912, 2918, 541, 1222]
79353 [1230, 922, 111, 2890, 1252]
51616 [58559, 4226, 2762, 8665, 110]
23333 [858, 1252, 1212, 527, 1213]
94595 [1252, 2959, 2716, 296, 1206]
112301 [1041, 2858, 509, 5618, 1673]
34971 [7361, 551, 5971, 2291, 3000]
6739 [923, 1228, 858, 903, 1207]
32341 [2959, 27773, 296, 3160, 32587]
75573 [293, 1291, 58559, 2542, 4878]
81773 [6016, 1732, 1276, 54503, 2028]
129746 [2858, 1221, 55820, 1208, 44555]
21055 [296, 1089, 1199, 608, 247]
11506 [1196, 919, 260, 318, 1203]
90725 [5060, 50, 1136, 2542, 1213]
129226 [541, 2959, 32, 1222, 111]
135505 [4226, 7361, 3949, 593, 2762]
13666 [1207, 1219, 1253, 969, 1252]
29334 [5669, 47, 39183, 36, 904]
55765 [4226, 593, 7153, 5952, 80463]
102373 [260, 1387, 3471, 3114, 1250]
115226 [5618, 745, 7361, 7153, 541]
51075 [1262, 1219, 858, 593, 527]
9454 [318, 2571, 1206, 904, 2542]
4507 [4993, 7153, 2019, 922, 899]
124373 [1203, 293, 2762, 1201, 2542]
95449 [1219, 1203, 1214, 33166, 904]
95216 [1136, 608, 111, 922, 7361]
64271 [1208, 1198, 1214, 56782, 79132]
133872 [318, 1196, 3552, 2502, 296]
17809 [5952, 1198, 4993, 260, 2571]
7554 [7153, 1219, 1193, 3703, 1029]
68710 [5952, 2571, 6942, 356, 7438]
83972 [296, 858, 1206, 1213, 1732]
11794 [1212, 904, 750, 1230, 111]
27102 [2571, 7153, 68954, 1270, 260]
1411 [6711, 3160, 50, 3949, 1617]
16127 [2076, 750, 5673, 6874, 50]
28748 [5618, 904, 2010, 4878, 4226]
71116 [553, 2804, 1036, 293, 2288]
12644 [356, 953, 1035, 1584, 7153]
103254 [2959, 33493, 296, 2542, 2502]
137838 [58559, 2858, 7361, 55820, 48516]
50192 [4973, 2291, 50, 79132, 60069]
106407 [318, 2396, 50, 3996, 1097]
115982 [741, 35836, 48385, 6874, 296]
60441 [2959, 47, 32, 1358, 3949]
99734 [3160, 2858, 3504, 1222, 903]
121308 [4306, 47, 2329, 3147, 223]
83882 [2959, 2571, 1036, 1198, 47]
120395 [1221, 1036, 3114, 2959, 8961]
89242 [2797, 539, 1088, 2424, 3408]
123327 [1207, 1299, 1252, 50, 720]
94325 [1198, 318, 4993, 1270, 356]
19310 [260, 6539, 595, 1291, 1]
34632 [1198, 1221, 1225, 3424, 922]
34770 [1610, 260, 2028, 49272, 589]
26198 [1198, 608, 296, 910, 750]
63799 [318, 296, 50, 1968, 2959]
39937 [1197, 1198, 318, 293, 38061]
27894 [2858, 2739, 2324, 1293, 1193]
73882 [904, 923, 1196, 858, 1219]
61567 [3578, 44555, 2231, 1732, 1089]
23068 [953, 54001, 5952, 1210, 2096]
53998 [904, 4226, 5618, 593, 750]
82202 [293, 1265, 1148, 2959, 1625]
79454 [1193, 4973, 608, 306, 858]
29261 [318, 593, 858, 1213, 1221]
96600 [1213, 1252, 904, 1228, 912]
99552 [3578, 1954, 2762, 1196, 527]
90583 [1210, 1196, 6539, 51662, 180]
51507 [1221, 6016, 1213, 590, 3949]
80414 [1250, 912, 527, 913, 904]
136754 [2959, 4993, 5952, 4973, 1136]
104349 [912, 1193, 1204, 1262, 1252]
91172 [1213, 912, 953, 1228, 913]
43683 [296, 551, 924, 778, 1732]
5768 [1221, 1266, 47, 1219, 1198]
66763 [923, 912, 1193, 904, 608]
9034 [1221, 908, 913, 162, 1079]
18683 [3114, 364, 593, 1198, 595]
82788 [296, 6874, 4993, 1206, 4848]
6917 [2019, 1221, 3424, 866, 111]
10721 [4993, 1193, 4973, 2858, 6711]
31995 [527, 1196, 2028, 2762, 1704]
45986 [4993, 6539, 1148, 260, 1287]
71781 [1136, 29, 551, 293, 1175]
84614 [111, 1219, 1221, 904, 1213]
38241 [356, 527, 924, 1198, 593]
56218 [5618, 2324, 4306, 4226, 1193]
18765 [2858, 2396, 56367, 4027, 17]
108223 [589, 2571, 1240, 593, 858]
122683 [1206, 2019, 1952, 6711, 1244]
75678 [2804, 4993, 1207, 1196, 318]
52898 [2571, 2353, 1584, 1, 110]
94449 [8622, 5669, 2019, 5618, 5995]
110609 [2000, 3527, 1265, 50, 1200]
27426 [296, 60069, 2700, 1, 778]
86066 [50, 1198, 4993, 593, 318]
35985 [7153, 5952, 48780, 4226, 1196]
129683 [1080, 4973, 750, 3000, 541]
64060 [1196, 260, 527, 1208, 1210]
79159 [1221, 1213, 260, 541, 1252]
23173 [111, 922, 1213, 6711, 912]
36003 [1214, 593, 1095, 4226, 1347]
26403 [750, 1213, 1104, 858, 909]
78392 [318, 858, 593, 1219, 1307]
133309 [4993, 912, 5952, 1221, 1284]
22693 [6016, 4226, 7361, 2858, 1221]
48392 [912, 1022, 68954, 1221, 908]
13069 [4226, 1193, 1203, 5995, 7153]
7835 [5618, 31658, 6016, 2858, 4226]
62644 [1208, 750, 1230, 541, 912]
39198 [318, 1136, 1197, 2542, 912]
103181 [6377, 7153, 5952, 1, 919]
50436 [356, 2762, 4995, 1580, 1270]
19279 [180, 2502, 318, 1215, 2858]
131347 [1208, 58559, 7361, 1228, 527]
62762 [2403, 6934, 1552, 3753, 1370]
42096 [1073, 1968, 1673, 593, 111]
52512 [1196, 1080, 750, 858, 32587]
89402 [1198, 593, 47, 1136, 111]
11747 [1207, 1256, 1219, 1172, 608]
10761 [1197, 345, 318, 1199, 1269]
49490 [260, 541, 912, 44555, 2501]
60978 [296, 3424, 923, 2700, 1208]
82635 [1197, 4014, 34405, 2762, 2396]
61168 [2959, 1036, 2571, 1221, 1201]
135819 [3104, 2762, 527, 2329, 3060]
85926 [1193, 858, 1206, 1288, 296]
135993 [1148, 720, 1270, 1291, 6539]
20528 [903, 1073, 475, 1225, 2186]
104824 [5618, 5971, 4993, 81591, 1527]
32344 [1387, 527, 318, 1302, 1]
52687 [1246, 296, 356, 1968, 1961]
107790 [1207, 1235, 914, 527, 1041]
81186 [1230, 111, 858, 296, 1208]
37814 [1221, 1193, 56782, 527, 1196]
80185 [7361, 55820, 903, 1252, 1228]
113487 [356, 58559, 7153, 3147, 858]
135694 [1358, 527, 1193, 778, 1968]
116317 [110, 780, 4993, 480, 2762]
50943 [1196, 1200, 260, 1387, 4993]
72929 [750, 5060, 912, 608, 922]
79902 [2571, 480, 3527, 4011, 3916]
78362 [44555, 1193, 910, 1945, 6377]
18415 [58, 913, 1225, 908, 33166]
93387 [296, 1136, 1213, 58559, 1288]
121713 [858, 1196, 1198, 1252, 1208]
81637 [4973, 34405, 58559, 1270, 4226]
91948 [47, 2329, 356, 2542, 293]
44780 [318, 7361, 2858, 1225, 5995]
4084 [903, 923, 858, 593, 908]
44952 [50, 48394, 1265, 7090, 2571]
125849 [1198, 1208, 1221, 1240, 1097]
112049 [356, 1270, 2571, 68358, 34162]
28467 [318, 2858, 1721, 5669, 2762]
107628 [318, 6016, 50, 904, 1193]
81000 [5952, 4306, 3969, 81845, 4993]
24027 [2571, 4993, 32, 1196, 1215]
60005 [4995, 7153, 2959, 1625, 6942]
91774 [318, 58559, 1210, 293, 50]
22658 [4993, 5952, 1198, 6377, 4886]
67569 [296, 5952, 527, 4027, 2329]
85623 [913, 2186, 969, 1207, 1387]
130767 [924, 111, 296, 1219, 922]
25071 [31658, 4973, 3396, 745, 904]
108082 [7153, 356, 527, 6539, 1210]
6921 [296, 4226, 858, 1221, 1213]
68351 [1221, 1208, 50, 1222, 2959]
2397 [47610, 2571, 48780, 2762, 1653]
136989 [858, 111, 922, 1288, 904]
29673 [260, 5952, 1221, 7361, 2959]
36225 [1219, 1221, 1212, 1256, 593]
46095 [924, 750, 1212, 858, 111]
36594 [5952, 1291, 3578, 1270, 3552]
32675 [912, 913, 1207, 904, 750]
75173 [344, 58559, 1291, 2706, 1]
10292 [1275, 6874, 58559, 1676, 1080]
66649 [1221, 296, 1219, 922, 5952]
62222 [4886, 6377, 53996, 2058, 8636]
93018 [162, 924, 2997, 541, 3160]
11246 [1221, 924, 903, 1212, 1254]
99522 [1197, 5618, 2324, 4973, 345]
8636 [750, 953, 1250, 44555, 898]
72838 [364, 595, 5952, 2081, 539]
135519 [1982, 1073, 1203, 223, 3114]
72401 [2700, 6377, 296, 69757, 46578]
46239 [318, 1089, 1222, 2329, 4262]
90143 [50, 1196, 912, 2959, 3996]
74628 [5349, 7293, 1704, 4701, 4018]
78259 [1250, 296, 1267, 919, 1208]
104725 [1270, 3421, 2716, 4361, 919]
74102 [912, 1221, 1252, 7361, 1201]
50574 [750, 922, 1265, 1267, 296]
66263 [364, 4306, 1028, 1198, 318]
34485 [1258, 541, 5952, 7361, 318]
74136 [318, 5952, 79132, 2028, 30749]
42124 [1527, 2571, 2572, 1088, 3793]
25411 [1148, 50, 6874, 4226, 6807]
106155 [780, 2571, 3578, 7153, 6934]
13092 [1253, 1219, 1214, 1982, 912]
69683 [1221, 4226, 7361, 4993, 1617]
70816 [1246, 2011, 1968, 7153, 46976]
66325 [1222, 2959, 4878, 1206, 4973]
92680 [1219, 2186, 1193, 1387, 2762]
113610 [1198, 1214, 858, 1208, 750]
69850 [6711, 1221, 2858, 1060, 318]
89703 [2571, 260, 1198, 3578, 356]
118860 [953, 356, 1954, 524, 2268]
23285 [1193, 2329, 3949, 1213, 903]
5504 [1408, 1197, 4993, 5418, 6539]
62925 [1221, 858, 1252, 1208, 912]
70346 [6711, 2858, 4993, 81591, 1196]
97628 [4848, 1206, 2600, 593, 4878]
86729 [1175, 903, 2010, 50, 48394]
89227 [2918, 47, 2028, 1, 2268]
113663 [1198, 1210, 1610, 527, 1396]
72465 [858, 1203, 903, 912, 2858]
8197 [527, 110, 1198, 32, 356]
89307 [50, 1136, 4878, 2692, 778]
84608 [8784, 6942, 2161, 2005, 2502]
106802 [4878, 296, 307, 1208, 306]
41818 [480, 1215, 593, 47, 2959]
9577 [541, 2959, 923, 296, 4878]
99754 [50, 111, 922, 1208, 1267]
69664 [4973, 7361, 1258, 1197, 318]
26222 [858, 5952, 593, 260, 904]
72266 [2076, 1208, 924, 4848, 923]
102565 [4973, 2858, 4226, 5995, 1201]
109286 [7361, 2858, 39183, 750, 5902]
102646 [1212, 2289, 745, 1148, 4848]
123352 [58559, 110, 79132, 2762, 1265]
91867 [912, 2858, 904, 969, 953]
126661 [1252, 1095, 1617, 1207, 912]
23523 [2324, 590, 1302, 953, 2329]
110706 [110, 318, 593, 1196, 5502]
8805 [7153, 541, 1214, 6539, 2959]
80987 [4973, 2959, 58559, 318, 1210]
14437 [1246, 4973, 2324, 318, 56367]
62375 [4993, 260, 293, 1197, 1968]
98494 [912, 2067, 1212, 1185, 527]
84802 [5971, 1285, 1148, 3949, 1206]
34419 [858, 912, 4034, 1249, 904]
44996 [1284, 1212, 1221, 908, 858]
111523 [910, 1252, 745, 1233, 1299]
3487 [4993, 260, 2542, 4011, 50]
84220 [589, 2028, 1573, 4855, 1221]
96447 [1101, 150, 1376, 318, 5952]
42886 [356, 5952, 1721, 1221, 2571]
3858 [111, 1282, 1193, 1263, 750]
11560 [1196, 5952, 296, 1200, 2019]
96780 [1206, 1089, 1148, 1213, 6874]
88267 [50, 1136, 4226, 47, 293]
5102 [50, 2324, 3897, 6942, 6377]
6964 [260, 1267, 1278, 5299, 3751]
12618 [6539, 4993, 4027, 3275, 8784]
86393 [1270, 593, 480, 1097, 1210]
78740 [750, 1221, 1212, 1219, 1136]
38372 [2019, 1221, 2959, 908, 1203]
90272 [47, 1358, 293, 1968, 858]
27074 [858, 47, 16, 1266, 1276]
40082 [2571, 5618, 7361, 68157, 55820]
43432 [2001, 5952, 2000, 2571, 1291]
113991 [1198, 58559, 1196, 3421, 1262]
100366 [4306, 588, 60069, 2571, 2858]
12973 [1387, 1221, 913, 1214, 903]
131031 [260, 1954, 1196, 589, 1240]
100556 [7153, 4993, 318, 597, 953]
2757 [5618, 924, 260, 1175, 1285]
43590 [318, 2762, 7153, 50, 47]
108123 [111, 16, 1213, 296, 1095]
30172 [904, 2396, 6377, 1252, 527]
125125 [1272, 1198, 1207, 1276, 2028]
5157 [2571, 1198, 7153, 1270, 2762]
61493 [2858, 1213, 4226, 16, 2542]
26214 [318, 4995, 1270, 2762, 1704]
93365 [3949, 1206, 1222, 44555, 1228]
102599 [2762, 50, 58559, 6539, 1]
5904 [111, 750, 2019, 527, 1213]
28830 [541, 1284, 1252, 923, 904]
52009 [2858, 800, 608, 1617, 3683]
63219 [50, 919, 527, 1193, 608]
95238 [1240, 1198, 30707, 1653, 527]
15108 [78499, 8961, 6377, 2804, 1197]
27764 [858, 2858, 1206, 1208, 924]

### Evaluation for all users

In [30]:
from collections import defaultdict

from surprise import Dataset, SVD
from surprise.model_selection import KFold


def precision_recall_at_k(predictions, k=10, threshold=3.5):
    """Return precision and recall at k metrics for each user"""

    # First map the predictions to each user.
    user_est_true = defaultdict(list)
    for uid, _, true_r, est, _ in predictions:
        user_est_true[uid].append((est, true_r))

    precisions = dict()
    recalls = dict()
    for uid, user_ratings in user_est_true.items():

        # Sort user ratings by estimated value
        user_ratings.sort(key=lambda x: x[0], reverse=True)

        # Number of relevant items
        n_rel = sum((true_r >= threshold) for (_, true_r) in user_ratings)

        # Number of recommended items in top k
        n_rec_k = sum((est >= threshold) for (est, _) in user_ratings[:k])

        # Number of relevant and recommended items in top k
        n_rel_and_rec_k = sum(
            ((true_r >= threshold) and (est >= threshold))
            for (est, true_r) in user_ratings[:k]
        )

        # Precision@K: Proportion of recommended items that are relevant
        # When n_rec_k is 0, Precision is undefined. We here set it to 0.

        precisions[uid] = n_rel_and_rec_k / n_rec_k if n_rec_k != 0 else 0

        # Recall@K: Proportion of relevant items that are recommended
        # When n_rel is 0, Recall is undefined. We here set it to 0.

        recalls[uid] = n_rel_and_rec_k / n_rel if n_rel != 0 else 0

    return precisions, recalls

In [31]:
precisions, recalls = precision_recall_at_k(predictions, k=5, threshold=4)

# Precision and recall can be averaged over all users
print(f"Macro Precision@5 = {sum(prec for prec in precisions.values()) / len(precisions)}")
print(f"Macro Recall@5 = {sum(rec for rec in recalls.values()) / len(recalls)}")

Macro Precision@5 = 0.8586666666666797
Macro Recall@5 = 0.08067802236177316

### Recommendation for a user

In [32]:
data.df[(data.df["userId"] == 29084)].shape

(418, 3)

In [33]:
inner_id = trainset.to_inner_uid(29084)   # convert raw → inner
trainset.knows_user(inner_id) 

#Don’t include users who aren’t in the trainset when computing Precision@K or Recall@K.
#Use a splitting method that ensures each user has ratings in both train and test.
#Otherwise, you’re evaluating the model on a cold-start scenario it wasn’t designed to handle

True

In [34]:
u = []
for t in testset:
    if t[0] == 29084:
        u.append(t)


testset2 = trainset.build_testset()
v = []
for t in testset2:
    if t[0] == 29084:
        v.append(t)

print(len(u))
print(len(v))

#Total user enties = 418 (305 + 113)
#user present in train set - 305
#user present in test set -  113

103
315

In [35]:
for p in predictions:
    if p.uid == 29084 and p.iid== 3409:
        print(p)

In [36]:
svd_model.predict(uid=29084, iid=3409, verbose=True)

user: 29084      item: 3409       r_ui = None   est = 3.19   {'was_impossible': False}

Prediction(uid=29084, iid=3409, r_ui=None, est=3.1905221513144006, details={'was_impossible': False})

In [37]:
movie_ids = []
for uid, user_ratings in top_n.items():
    if uid == 29084:
        movie_ids = [iid for (iid,_) in user_ratings]
        print(uid, movie_ids)

29084 [293, 4973, 593, 44191, 56367]

In [38]:
upred = pd.DataFrame(top_n[29084], columns=["movieId", "prediction"])

udf = data.df[(data.df["userId"] == 29084)].sort_values(by="rating")[::-1].reset_index()
utrue = udf[udf["movieId"].isin(movie_ids)]
utrue.merge(upred, on="movieId")

     index  userId  movieId  rating  prediction
0  4270881   29084     4973     5.0    4.168186
1  4270485   29084      293     5.0    4.196810
2  4270525   29084      593     5.0    4.109068
3  4271236   29084    56367     4.5    4.106574
4  4271165   29084    44191     4.0    4.107431

In [39]:
#Precision@K only cares about the quality of the top‑K list. Since all 5 were relevant, precision is perfect.
#Recall@K cares about coverage. Even though the top‑5 were all correct, they represent only a small fraction of the user’s total relevant items. That’s why recall is low.

print(precisions[29084])

# t[0] == 29084 and t[2] > 3.5 = 48 
# 5/48 = 0.104
print(recalls[29084])

1.0
0.11627906976744186

### Leave one out split 
Every user is represented in both train and test. That way, you won’t run into “user not in trainset” mismatches.

In [40]:
data.df.shape

(2353665, 3)

In [41]:
# LeaveOneOut split: each user has at least one rating in test
loo = LeaveOneOut(n_splits=1, random_state=42)

for trainset, testset in loo.split(data):
    print("Trainset size:", trainset.n_ratings)
    print("Testset size:", len(testset))

Trainset size: 2348665
Testset size: 5000

In [42]:
# Check that every user is in trainset
all_users = set(filtered['userId'].unique())
train_users = set(trainset.to_raw_uid(i) for i in range(trainset.n_users))
print("Users missing from trainset:", all_users - train_users)  # should be empty

Users missing from trainset: set()

## Implicit Feedback - SVD - Numpy

In [ ]:
# Matrix factorization via SVD
#TODO
U, sigma, Vt = np.linalg.svd(user_item, full_matrices=False)
pred_matrix = np.dot(U, np.dot(np.diag(sigma), Vt))

## Implicit Feedback - ALS

In [43]:
from scipy import sparse
import implicit

C:\Users\nedwi\AppData\Local\Programs\Python\Python312\312-env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [44]:
path = os.path.abspath(os.path.join((os.getcwd()),  os.pardir, "data\\retail\\Online_Retail.xlsx")) 
df_raw = pd.read_excel(path)
print(df_raw.shape)
df_raw.head()

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [45]:
df_raw["InvoiceNo"].nunique()

25900

In [46]:
print(f"Total users: {df_raw["CustomerID"].nunique()}")
print(f"Total items: {df_raw["StockCode"].nunique()}")

Total users: 4372
Total items: 4070

In [47]:
#count of unique Items bought per customer
df_items_per_cust = (
    df_raw.groupby(["CustomerID"]).agg({"StockCode": "nunique"}).reset_index()
)
df_items_per_cust.columns = ["CustomerID", "Count_item_cust"]
df_items_per_cust

      CustomerID  Count_item_cust
0        12346.0                1
1        12347.0              103
2        12348.0               22
3        12349.0               73
4        12350.0               17
...          ...              ...
4367     18280.0               10
4368     18281.0                7
4369     18282.0               12
4370     18283.0              263
4371     18287.0               59

[4372 rows x 2 columns]

In [48]:
# Setting of Threshold
item_in_cust_threshold = 6

# Filtering Results
mask = df_items_per_cust["Count_item_cust"] >= item_in_cust_threshold
valid_cust = set(df_items_per_cust.loc[mask, "CustomerID"].tolist())

df_filter_cust = df_raw[df_raw["CustomerID"].isin(valid_cust)].copy()
invoiceno_filter_cust = set(df_filter_cust["InvoiceNo"].tolist())

In [49]:
#count of unique customers who bought that item
df_custs_per_item = (
    df_raw.groupby(["StockCode"]).agg({"CustomerID": "nunique"}).reset_index()
)
df_custs_per_item.columns = ["StockCode", "Count_cust_item"]
df_custs_per_item["Count_cust_item"].value_counts()

Count_cust_item
0      386
1      189
2      145
3      116
6       83
      ...
252      1
392      1
858      1
276      1
379      1
Name: count, Length: 380, dtype: int64

In [50]:
# Set threshold
cust_in_item_threshold = 6
#Filter Results
mask = df_custs_per_item["Count_cust_item"] >= cust_in_item_threshold
valid_stockcode = set(df_custs_per_item.loc[mask, "StockCode"].tolist())

df_filter_item = df_raw[df_raw["StockCode"].isin(valid_stockcode)].copy()
invoiceno_filter_item = set(df_filter_item["InvoiceNo"].tolist())

In [51]:
invoiceno_intersect = set.intersection(invoiceno_filter_item, invoiceno_filter_cust)
df_filter_cust_item = df_raw[df_raw["InvoiceNo"].isin(invoiceno_intersect)].copy()

In [52]:
df_filter_cust_item.shape

(405521, 8)

In [53]:
#Generating Customer and Item IDs
unique_customers = df_filter_cust_item["CustomerID"].unique()
cust_ids = dict(
    zip(unique_customers, np.arange(unique_customers.shape[0], dtype=np.int32))
)
print(len(cust_ids))

unique_items = df_filter_cust_item["StockCode"].unique()
item_ids = dict(zip(unique_items, np.arange(unique_items.shape[0], dtype=np.int32)))
print(len(item_ids))

4017
3671

In [54]:
df_filter_cust_item["cust_id"] = df_filter_cust_item["CustomerID"].apply(
    lambda i: cust_ids[i]
)
df_filter_cust_item["item_id"] = df_filter_cust_item["StockCode"].apply(
    lambda i: item_ids[i]
)

df_filter_cust_item.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,cust_id,item_id
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,0,0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,0,2
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,3
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,4

In [55]:
df_cust_item_qty = (
    df_filter_cust_item.groupby(["cust_id", "item_id"])
    .agg({"Quantity": "sum"})
    .reset_index()
)
df_cust_item_qty

        cust_id  item_id  Quantity
0             0        0       122
1             0        1       122
2             0        2       108
3             0        3       110
4             0        4       104
...         ...      ...       ...
266591     4016     3219         6
266592     4016     3271        12
266593     4016     3320        25
266594     4016     3452         4
266595     4016     3482         6

[266596 rows x 3 columns]

In [56]:
# Create Sparse Matrix
sparse_customer_item = sparse.csr_matrix(
    (
        df_cust_item_qty["Quantity"].astype(float),
        (df_cust_item_qty["cust_id"], df_cust_item_qty["item_id"]), #shape
    ) 
)
sparse_customer_item

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 266596 stored elements and shape (4017, 3671)>

In [57]:
# Initialize an Alternating Least Squares model
model = implicit.als.AlternatingLeastSquares(factors=50)
# Train on user-item sparse matrix
model.fit(sparse_customer_item)

C:\Users\nedwi\AppData\Local\Programs\Python\Python312\312-env\Lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning: OpenBLAS is configured to use 4 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00,  7.51it/s]

In [58]:
print(model.user_factors.shape)
print(model.item_factors.shape)

(4017, 50)
(3671, 50)

In [59]:
# Get recommendations
cust_id = 0
ids, scores = model.recommend(
    cust_id, sparse_customer_item[cust_id], N=5, filter_already_liked_items=False
)

len(scores)

5

In [60]:
df_item_desc = df_filter_cust_item.groupby("StockCode")[["Description", "item_id"]].first().reset_index()
print(df_item_desc.shape)

(3671, 3)

In [61]:
df_item_desc.head()

  StockCode                   Description  item_id
0     10002   INFLATABLE POLITICAL GLOBE        31
1     10080      GROOVY CACTUS INFLATABLE     2761
2     10120                  DOGGY RUBBER     1334
3     10125       MINI FUNKY DESIGN TAPES      502
4     10133  COLOURING PENCILS BROWN TUBE      460

In [62]:
list_stockcode = df_item_desc[df_item_desc["item_id"].isin(ids)]["StockCode"].tolist()
list_desc = df_item_desc[df_item_desc["item_id"].isin(ids)]["Description"].tolist()
df_recommendations = pd.DataFrame(
    {
        "Stockcode": list_stockcode,
        "Description": list_desc,
        "score": scores,
        "already_liked": np.in1d(ids, sparse_customer_item[cust_id].indices),
    }
)
df_recommendations

   Stockcode                        Description     score  already_liked
0      21733   RED HANGING HEART T-LIGHT HOLDER  1.259391          False
1      22111       SCOTTIE DOG HOT WATER BOTTLE  1.155702          False
2      22113        GREY HEART HOT WATER BOTTLE  1.147058          False
3      22834        HAND WARMER BABUSHKA DESIGN  1.109052          False
4      71477  COLOUR GLASS. STAR T-LIGHT HOLDER  1.052645           True

In [63]:

#Finding similar items 
#Given a particular item, a list of closest items can be generated

ref_item_id = df_filter_cust_item["item_id"].unique()
item_arr, score_arr = model.similar_items(ref_item_id, N=10)

In [64]:
df_item_temp = pd.DataFrame(item_arr)
df_item_temp["Ref Item ID"] = ref_item_id
df_item_rank = pd.melt(
    df_item_temp,
    id_vars=["Ref Item ID"],
    var_name="Item Rank",
    value_name="Related Item ID",
)
df_score_temp = pd.DataFrame(score_arr)
df_score_temp["Ref Item ID"] = ref_item_id
df_score_rank = pd.melt(
    df_score_temp, id_vars=["Ref Item ID"], var_name="Item Rank", value_name="Score"
)
df_item_score = df_item_rank.merge(
    df_score_rank, how="inner", on=["Ref Item ID", "Item Rank"]
)

In [65]:
df_item_score

       Ref Item ID Item Rank  Related Item ID     Score
0                0         0                0  1.000000
1                1         0                1  1.000000
2                2         0                2  1.000000
3                3         0                3  1.000000
4                4         0                4  1.000000
...            ...       ...              ...       ...
36705         3666         9             3173  0.880004
36706         3667         9             3173  0.880147
36707         3668         9             3173  0.880212
36708         3669         9             3173  0.880144
36709         3670         9             3201  0.390938

[36710 rows x 4 columns]

In [66]:
# Time based split

In [67]:
import pandas as pd

# Example: user activity log with monthly churn labels
data = pd.DataFrame({
    "user_id": [1,1,1,2,2,2],
    "month": pd.to_datetime(["2024-12","2025-01","2025-02",
                              "2024-12","2025-01","2025-02"]),
    "logins": [10, 8, 5, 7, 6, 2],
    "churn_label": [0, 0, 1, 0, 1, 1]  # 1 = churn in that month
})

# -----------------------------
# 1. Build features snapshot
# -----------------------------
# Features are based on past month activity
X = data[["user_id","month","logins"]]

# -----------------------------
# 2. Align labels with horizon
# -----------------------------
# For 1-month ahead churn prediction:
# Label = churn in the NEXT month
data["label_next_month"] = data.groupby("user_id")["churn_label"].shift(-1)

# Now each row has features from month t and label from month t+1
aligned = data.dropna(subset=["label_next_month"])

In [68]:
data

   user_id      month  logins  churn_label  label_next_month
0        1 2024-12-01      10            0               0.0
1        1 2025-01-01       8            0               1.0
2        1 2025-02-01       5            1               NaN
3        2 2024-12-01       7            0               1.0
4        2 2025-01-01       6            1               1.0
5        2 2025-02-01       2            1               NaN

In [69]:
aligned

   user_id      month  logins  churn_label  label_next_month
0        1 2024-12-01      10            0               0.0
1        1 2025-01-01       8            0               1.0
3        2 2024-12-01       7            0               1.0
4        2 2025-01-01       6            1               1.0

In [70]:
train = aligned[aligned["month"] <= "2024-12"]
test  = aligned[(aligned["month"] >= "2025-01") & (aligned["month"] <= "2025-02")]

X_train, y_train = train[["logins"]], train["label_next_month"]
X_test, y_test   = test[["logins"]], test["label_next_month"]

In [71]:
train

   user_id      month  logins  churn_label  label_next_month
0        1 2024-12-01      10            0               0.0
3        2 2024-12-01       7            0               1.0

In [72]:
test

   user_id      month  logins  churn_label  label_next_month
1        1 2025-01-01       8            0               1.0
4        2 2025-01-01       6            1               1.0