In [128]:
from xgboost import XGBClassifier, XGBModel
import xgboost as xg
from sklearn.metrics import accuracy_score, mean_squared_error, roc_auc_score 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

In [2]:
loan = pd.read_csv(os.path.abspath(os.path.join(os.getcwd() + '\\..\\data\\train_loanpred.csv')))
tree_loan = loan.loc[:, ~loan.columns.isin(["Loan_ID"])]
print(tree_loan.shape)

(614, 12)

In [83]:
tree_loan["Loan_Status"].value_counts()

Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [65]:
loan_test = pd.read_csv(os.path.abspath(os.path.join(os.getcwd() + '\\..\\data\\test_loanpred.csv')))
x_test = loan_test.loc[:, ~loan_test.columns.isin(["Loan_ID"])]
print(x_test.shape)

(367, 11)

In [4]:
tree_loan.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y

In [3]:
tree_loan.isnull().sum().sort_values(ascending=False)

Credit_History       50
Self_Employed        32
LoanAmount           22
Dependents           15
Loan_Amount_Term     14
Gender               13
Married               3
Education             0
CoapplicantIncome     0
ApplicantIncome       0
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
X = tree_loan.iloc[:, :-1]
Y = tree_loan.iloc[:, -1]
x_train, x_val, y_train, y_val = train_test_split(X, Y, test_size=0.2, random_state=22)

In [28]:
cat_cols = ["Property_Area", "Dependents", "Gender", "Married", "Education", "Self_Employed"]

In [69]:
for col in cat_cols: 
    x_train[col] = x_train[col].astype('category')
    x_val[col] =  x_val[col].astype('category')
    x_test[col] = x_test[col].astype('category')

C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')
C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')
C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')
C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')
C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')
C:\Users\nedwi\AppData\Local\Temp\ipykernel_19732\1117333741.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test[col] = x_test[col].astype('category')

In [71]:
x_train.dtypes

Gender               category
Married              category
Dependents           category
Education            category
Self_Employed        category
ApplicantIncome         int64
CoapplicantIncome       int64
LoanAmount            float64
Loan_Amount_Term      float64
Credit_History        float64
Property_Area        category
dtype: object

In [33]:
y_train_mapped = y_train.map(lambda x: 1 if x == 'Y' else 0)
y_val_mapped = y_val.map(lambda x: 1 if x == 'Y' else 0)

In [32]:
model = XGBClassifier(enable_categorical=True) 
model.fit(x_train, y_train_mapped)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [35]:
pred = model.predict(x_val)
accuracy_score(y_val_mapped, pred)

0.7154471544715447

In [82]:
pos_val = y_train_mapped[y_train_mapped == 0].shape[0]/ y_train_mapped[y_train_mapped == 1].shape[0]
pos_val

0.4526627218934911

In [159]:
xgb = XGBClassifier(n_estimators=500, 
                    base_score=0.5,
                    early_stopping_rounds=20, 
                    learning_rate = 0.1,
                    subsample = 0.8,
                    max_depth=3,
                    tree_method = 'auto', #hist
                    max_bin = 256,
                    objective="binary:logistic",
                    eval_metric="logloss",
                    gamma=0.1,
                    reg_alpha = 0,
                    reg_lambda = 1,
                    enable_categorical=True,
                    missing=np.nan,
                    #scale_pos_weight=pos_val,
                    random_state=42
                    )

xgb.fit(x_train, y_train_mapped, eval_set=[(x_train, y_train_mapped), (x_val,y_val_mapped)], verbose=True)
#dont use testing data in eval

[0]	validation_0-logloss:0.65479	validation_1-logloss:0.65685
[1]	validation_0-logloss:0.62304	validation_1-logloss:0.62757
[2]	validation_0-logloss:0.59601	validation_1-logloss:0.60237
[3]	validation_0-logloss:0.57300	validation_1-logloss:0.58103
[4]	validation_0-logloss:0.55411	validation_1-logloss:0.56237
[5]	validation_0-logloss:0.53813	validation_1-logloss:0.54571
[6]	validation_0-logloss:0.52416	validation_1-logloss:0.53115
[7]	validation_0-logloss:0.51159	validation_1-logloss:0.52103
[8]	validation_0-logloss:0.50134	validation_1-logloss:0.51204
[9]	validation_0-logloss:0.49171	validation_1-logloss:0.50175
[10]	validation_0-logloss:0.48387	validation_1-logloss:0.49528
[11]	validation_0-logloss:0.47691	validation_1-logloss:0.48793
[12]	validation_0-logloss:0.47015	validation_1-logloss:0.48165
[13]	validation_0-logloss:0.46392	validation_1-logloss:0.47959
[14]	validation_0-logloss:0.45946	validation_1-logloss:0.47713
[15]	validation_0-logloss:0.45487	validation_1-logloss:0.47654
[16]	validation_0-logloss:0.44995	validation_1-logloss:0.47413
[17]	validation_0-logloss:0.44509	validation_1-logloss:0.47100
[18]	validation_0-logloss:0.44154	validation_1-logloss:0.46782
[19]	validation_0-logloss:0.43748	validation_1-logloss:0.46763
[20]	validation_0-logloss:0.43243	validation_1-logloss:0.46664
[21]	validation_0-logloss:0.42983	validation_1-logloss:0.46540
[22]	validation_0-logloss:0.42559	validation_1-logloss:0.46489
[23]	validation_0-logloss:0.42175	validation_1-logloss:0.46257
[24]	validation_0-logloss:0.41901	validation_1-logloss:0.46005
[25]	validation_0-logloss:0.41486	validation_1-logloss:0.46041
[26]	validation_0-logloss:0.41239	validation_1-logloss:0.45660
[27]	validation_0-logloss:0.40985	validation_1-logloss:0.45702
[28]	validation_0-logloss:0.40777	validation_1-logloss:0.45632
[29]	validation_0-logloss:0.40478	validation_1-logloss:0.45399
[30]	validation_0-logloss:0.40302	validation_1-logloss:0.45485
[31]	validation_0-logloss:0.40101	validation_1-logloss:0.45538
[32]	validation_0-logloss:0.39798	validation_1-logloss:0.45539
[33]	validation_0-logloss:0.39591	validation_1-logloss:0.45208
[34]	validation_0-logloss:0.39283	validation_1-logloss:0.45399
[35]	validation_0-logloss:0.38939	validation_1-logloss:0.45119
[36]	validation_0-logloss:0.38679	validation_1-logloss:0.45135
[37]	validation_0-logloss:0.38500	validation_1-logloss:0.45145
[38]	validation_0-logloss:0.38242	validation_1-logloss:0.45143
[39]	validation_0-logloss:0.37986	validation_1-logloss:0.45262
[40]	validation_0-logloss:0.37838	validation_1-logloss:0.45391
[41]	validation_0-logloss:0.37738	validation_1-logloss:0.45262
[42]	validation_0-logloss:0.37510	validation_1-logloss:0.45369
[43]	validation_0-logloss:0.37342	validation_1-logloss:0.45138
[44]	validation_0-logloss:0.37264	validation_1-logloss:0.45077
[45]	validation_0-logloss:0.36977	validation_1-logloss:0.44882
[46]	validation_0-logloss:0.36728	validation_1-logloss:0.45068
[47]	validation_0-logloss:0.36590	validation_1-logloss:0.45087
[48]	validation_0-logloss:0.36305	validation_1-logloss:0.45185
[49]	validation_0-logloss:0.36206	validation_1-logloss:0.45157
[50]	validation_0-logloss:0.35998	validation_1-logloss:0.44984
[51]	validation_0-logloss:0.35922	validation_1-logloss:0.44951
[52]	validation_0-logloss:0.35832	validation_1-logloss:0.45056
[53]	validation_0-logloss:0.35546	validation_1-logloss:0.45452
[54]	validation_0-logloss:0.35422	validation_1-logloss:0.45528
[55]	validation_0-logloss:0.35267	validation_1-logloss:0.45519
[56]	validation_0-logloss:0.35154	validation_1-logloss:0.45493
[57]	validation_0-logloss:0.35020	validation_1-logloss:0.45558
[58]	validation_0-logloss:0.34951	validation_1-logloss:0.45608
[59]	validation_0-logloss:0.34788	validation_1-logloss:0.45617
[60]	validation_0-logloss:0.34585	validation_1-logloss:0.45766
[61]	validation_0-logloss:0.34443	validation_1-logloss:0.45689
[62]	validation_0-logloss:0.34288	validation_1-logloss:0.45755
[63]	validation_0-logloss:0.34122	validation_1-logloss:0.45748
[64]	validation_0-logloss:0.34056	validation_1-logloss:0.45777
[65]	validation_0-logloss:0.33855	validation_1-logloss:0.45905

XGBClassifier(base_score=0.5, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=20,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=256,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [160]:
print(f'Best iteration is {xgb.best_iteration} and \
   \n trainging best score is {xgb.evals_result()["validation_0"]["logloss"][xgb.best_iteration]} \
    \n validation best score is {xgb.best_score} after early stopping')

Best iteration is 45 and
 trainging best score is 0.3697728935151139
 validation best score is 0.44882087167201 after early stopping

In [162]:
xgb_pred = xgb.predict(x_val)
accuracy_score(y_val_mapped, xgb_pred)

0.8048780487804879

In [153]:
import xgboost as xgb 
dtrain = xgb.DMatrix(x_train, label=y_train_mapped, enable_categorical=True) 
params = { 
                    #'n_estimators':500, 
                    'base_score':0.5,
                    #'early_stopping_rounds':20, 
                    'learning_rate': 0.1,
                    'subsample' : 0.8,
                    'max_depth':3,
                    'tree_method' : 'auto', #hist
                    'max_bin' :256,
                    'objective':"binary:logistic",
                    'eval_metric':"logloss",
                    'gamma':0.1,
                    'reg_alpha': 0,
                    'reg_lambda': 1,
                    'enable_categorical':True,
         }
cv_results = xgb.cv( params, dtrain, num_boost_round=1000, nfold=5, early_stopping_rounds=20, seed=42 )
cv_results

C:\Users\nedwi\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:225: UserWarning: [22:55:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "enable_categorical" } are not used.

  return getattr(self.bst, name)(*args, **kwargs)
C:\Users\nedwi\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:231: UserWarning: [22:55:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "enable_categorical" } are not used.

  self.bst.update(self.dtrain, iteration, fobj)

    train-logloss-mean  train-logloss-std  test-logloss-mean  test-logloss-std
0             0.653714           0.002339           0.657214          0.005023
1             0.622883           0.004325           0.630270          0.009954
2             0.597019           0.006709           0.609193          0.015009
3             0.573857           0.008034           0.588795          0.019070
4             0.554628           0.009049           0.572168          0.022841
5             0.537200           0.009935           0.558697          0.026405
6             0.523362           0.010597           0.547881          0.029770
7             0.510387           0.011149           0.538716          0.033247
8             0.498933           0.011704           0.532234          0.036683
9             0.489658           0.012502           0.526070          0.039213
10            0.481191           0.013177           0.520343          0.041333
11            0.473151           0.013591           0.515307          0.043431
12            0.466269           0.013969           0.511225          0.045800
13            0.460484           0.013875           0.507404          0.047303
14            0.454687           0.014207           0.503710          0.049266
15            0.449304           0.014450           0.502379          0.050668
16            0.444620           0.015309           0.499948          0.052666
17            0.440218           0.015447           0.498645          0.054682
18            0.435951           0.015951           0.497418          0.055936
19            0.431217           0.016569           0.496160          0.056321
20            0.427257           0.017497           0.495904          0.057993
21            0.423836           0.017000           0.495214          0.059582

In [161]:
cv_results["train-logloss-mean"].argmin()

np.int64(21)

In [154]:
best_num_boost_round = len(cv_results)
best_num_boost_round

22

In [155]:
xgb_clf = XGBClassifier( n_estimators=best_num_boost_round, **params ) 
xgb_clf.fit(x_train, y_train_mapped) 
preds = xgb_clf.predict(x_val)

In [156]:
accuracy_score(y_val_mapped, preds)

0.8292682926829268

In [75]:
pred = xgb.predict(x_test)

In [ ]:
x_cat= pd.get_dummies(x_train[cat_cols], drop_first=True)
x_val_cat = pd.get_dummies(x_val[cat_cols], drop_first=True)
x_val_cat = x_val_cat.reindex(columns=x_cat.columns, fill_value=0)